spring:
  application:
    name: req-producer-service
  profiles:
    group:
      "dev": "base,dev"
      "prod": "base,prod"
      "uat": "base,uat"

server:
  port: 9093
  servlet:
    context-path: /
    encoding:
      charset: 'UTF-8'
      enabled: true
      force: true
  shutdown: graceful
logging:
  level:
    sun:
      rmi: ERROR
    javax:
      management:
        remote:
          rmi: ERROR