version: '3'

networks:
  app-tier:
    driver: bridge

services:
  redis:
    container_name: redis-server
    hostname: redis
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_PASSWORD=12345678aA@
    ports:
    - "6379:6379"  
    networks:
      - app-tier
    
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379:1:12345678aA@
    ports:
    - "8081:8081"
    networks:
      - app-tier