spring:
  application:
    name: gateway-service

server:
  port: 9091
  servlet:
    context-path: /
    encoding:
      charset: 'UTF-8'
      enabled: true
      force: true
#logging:
#  level:
#    sun:
#      rmi: ERROR
#    javax:
#      management:
#        remote:
#          rmi: ERROR